name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "!main"

jobs:
  ci:
    name: Continuous Integration

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build & Test
        run: |
          yarn run lint
          yarn run build
